# Generated by Django 3.1.5 on 2021-02-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'ประกาศ', 'verbose_name_plural': 'ประกาศ'},
        ),
    ]
