# Generated by Django 3.1.7 on 2021-03-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210312_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='token',
            new_name='order_no',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='slip',
            field=models.ImageField(blank=True, upload_to='transfer_slip'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('checking', 'กำลังตรวจสอบ'), ('complete', 'สำเร็จ')], max_length=10),
        ),
    ]
