# Generated by Django 3.1.7 on 2021-03-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210313_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
