# Generated by Django 3.1.7 on 2021-03-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210317_0558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='Address',
        ),
    ]
