# Generated by Django 3.1.7 on 2021-03-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210317_0600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='BillingAddress',
        ),
    ]
