# Generated by Django 3.1.7 on 2021-03-16 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_no',
        ),
    ]
