# Generated by Django 3.1.7 on 2021-03-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210317_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('รอชำระเงิน', 'รอชำระเงิน'), ('ชำระเงินแล้ว-รอตรวจสอบ', 'ชำระเงินแล้ว-รอตรวจสอบ'), ('กำลังจัดส่ง', 'กำลังจัดส่ง'), ('จัดส่งสินค้าแล้ว', 'จัดส่งสินค้าแล้ว'), ('ไม่ผ่านการตรวจสอบ', 'ไม่ผ่านการตรวจสอบ')], max_length=255),
        ),
    ]
