# Generated by Django 3.1.7 on 2021-03-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
